import { Platform } from './platform.enum';

export interface Top100Apps {
  app_id: number;
  canonical_country: string;
  name: string;
  publisher_name: string;
  publisher_id: number;
  humanized_name: string;
  icon_url: string;
  os: Platform;
  id: number;
  appId: number;
  icon: string;
  iconUrl: string;
  url: string;
  categories: number[];
  valid_countries: string[];
  app_view_url: string;
  publisher_profile_url: string;
  release_date: Date;
  updated_date: Date;
  in_app_purchases: boolean | string;
  shows_ads: boolean | null;
  buys_ads: boolean | null;
  rating: number;
  price: number;
  global_rating_count: number;
  rating_count: number;
  rating_count_for_current_version: number;
  rating_for_current_version: number;
  version: string;
  apple_watch_enabled: null;
  apple_watch_icon: null;
  imessage_enabled: boolean | null;
  imessage_icon: null | string;
  humanized_worldwide_last_month_downloads: string;
  humanized_worldwide_last_month_revenue: string;
  bundle_id: string;
  support_url: string;
  website_url: null | string;
  privacy_policy_url: string;
  eula_url: null | string;
  publisher_email: null;
  publisher_address: null;
  publisher_country: null | string;
  feature_graphic: null | string;
  short_description: null;
  advisories: string[];
  content_rating: string;
  rank: number;
  delta: number;
  downloads_revenue_date: Date;
}
